{% set name = "solvespace" %}
{% set version = "2.4.2" %}
{% set sha256 = "0aee9bbb0fad109800e4d8f899fdd23c3d8c46019bb5ac57959023ae61f3fcc2" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}_fc.tar.gz
    url: https://github.com/realthunder/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    skip: true  # [py<36]

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
        - swig
        - ninja
    host:
        - python 3.9
    run:
        - python 3.9

# test: # disable test for now, as on macos it crashes somehow
#     imports:
#         - slvs
